// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Movie struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Rate        string `json:"rate"`
	Year        string `json:"year"`
	Description string `json:"description"`
	Genres      string `json:"genres"`
	Duration    string `json:"duration"`
	ImageURL    string `json:"imageURL"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Query struct {
}
