apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies-ingress
spec:
  ingressClassName: "gce"
  rules:
    - host: movies-23df5e8a.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 80
