name: Go CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run go vet
        run: go list ./... | grep -v /internal/scraper | xargs go vet -e internal/scraper

      - name: Run go fmt
        run: go fmt ./...

      - name: Run make test
        run: go test ./tests
