name: Go CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run go vet
        run: |
          for pkg in $(go list ./... | grep -v /internal/scraper); do
            go vet -all $$pkg || true
          done
      - name: Run go fmt
        run: go fmt ./...
